### ISSUE TITLE
sleep: invalid option -- '1'

### ISSUE THREAD

**Issue by everydaylearner** [lux4rd0/sense-collector#10]
Anyone getting the following error:

sleep: invalid option -- '1' 

Constantly keeps showing up in the logs! 

Thank you!

**Comment by CodaBool** [comment]
Not sure what your use case is but I just ended up switching to the [Python unofficial API](https://github.com/scottbonline/sense) since all I really want was the usage and solar production over each day. 

here is what my resulting python code. I have it run every minute and write to a database. [Full code](https://github.com/CodaBool/solar/tree/main)

```py
from sense_energy import Senseable
from dotenv import load_dotenv
import os

load_dotenv()
sense = Senseable()
sense.authenticate("secret@gmail.com", os.environ.get("PASSWORD"))
sense.update_realtime()
print ("usage", int(sense.active_power), "W")
print ("solar", int(sense.active_solar_power), "W")
```

**Comment by everydaylearner** [comment]
ohh i see!!!  it looks like you are writing to Mongo db not influx.  do you have any samples to write to influxdb2 by any chance? :)

**Comment by CodaBool** [comment]
I unfortunately don't because I've never worked with influx. 

Part of the reason I moved to the unofficial API. Because it was db agnostic

**Comment by CodaBool** [comment]
Chatgpt would probably be happy to write that for you lol

Chat.openai.com

**Comment by lux4rd0** [comment]
Sleep error was an annoying side effect of the old code. Sorry about that mess!! The new version is rewritten! Hope you can try it out!
