### ISSUE TITLE
Device Overview dashboard doesn't show any data

### ISSUE THREAD

**Issue by paradizelost** [lux4rd0/sense-collector#7]
didn't know where else to submit this bug report, but i get this from the device overview dashboard.
No data fills in and all boxes show the same error, except for the plugin not found message.
![image](https://user-images.githubusercontent.com/22059408/200933568-824aa5e7-a982-47db-97a8-0af50e98444b.png)

![image](https://user-images.githubusercontent.com/22059408/200933387-c950427d-6179-4fe1-ba99-8a5deadf141f.png)

**Comment by paradizelost** [comment]
all other dashboards appear to be functional

**Comment by lux4rd0** [comment]
Can you let me know if this is still an issue with the new version of the collector? At the time, the API was hosed from Sense, and a billion items were shoved into my collector. (Ummm - one way or the other! LOL) And it caused a billion devices to be added. Because I use drop downs to filter devices - it's too many for a regular post to handle - Grafana barfs up a 400 error because the message is too large. The only way I found to fix it was to dump out - or clear all of the devices... Sorry for the late response! I ran into the same issue!!
